name: GitHub Profile README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Rebuild README.md file
        run: |-
          npm run start
          cat README.md
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email "mailtobolaji+readmebot@gmail.com"
          git config --global user.name "BA README Bot"
          git commit -m "docs: update README.md (scheduled)" -a || exit 0
          git push
